### ISSUE TITLE
RuntimeException: Unable to start activity ComponentInfo: android.view.InflateException: Binary XML file line #31:

### ISSUE THREAD

**Issue by esrabindra** [MAXDeliveryNG/slideview#14]
When i run the project it crashed every time. I added dependencies and follow the step that are listed on github. But get problem while running the project,
Unable to start activity ComponentInfo{com.app.lifecycle/com.test.lifecycle.MainActivity}: android.view.InflateException: Binary XML file line #31: Binary XML file line #31: Error inflating class ng.max.slideview.SlideView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
        at android.app.ActivityThread.access$1100(ActivityThread.java:221)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7225)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: android.view.InflateException: Binary XML file line #31: Binary XML file line #31: Error inflating class ng.max.slideview.SlideView

**Comment by kizitonwose** [comment]
Can you share how you defined the class in XML?

**Comment by AhmedSaadShrief** [comment]
Same problem
